# Generated by Django 5.1.3 on 2024-11-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
