# Generated by Django 5.1.3 on 2024-11-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product_image',
            field=models.CharField(max_length=255),
        ),
    ]
